### ISSUE TITLE
unzip shrec17

### ISSUE THREAD

**Issue by bring728** [auniquesun/viewformer#1]
hi! thanks for sharing your great work and shrec17 rendering!

i have downloaded your shrec17 rendering. but i cant unzip these files.. these files doesnt have extension. how can i unzip these files?

**Comment by auniquesun** [comment]
You can refer to the `README.md` in the shrec17 folder. There is an instruction of generating the `.zip` file and unzipping it.

**Comment by bring728** [comment]
Ah, Thank you! my mistakes!
